### ISSUE TITLE
Docker Container Fails to Run

### ISSUE THREAD

**Issue by shubhamoy** [dvf/blockchain#29]
I tried to run the docker container after a successful build and ran into this error:

```
Traceback (most recent call last):
  File "/app/blockchain.py", line 12, in <module>
    class Blockchain:
  File "/app/blockchain.py", line 135, in Blockchain
    def last_block(self) -> Dict[str: Any]:
  File "/usr/local/lib/python3.6/typing.py", line 682, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/typing.py", line 1106, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/local/lib/python3.6/typing.py", line 1106, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/local/lib/python3.6/typing.py", line 374, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Parameters to generic types must be types. Got slice(<class 'str'>, typing.Any, None).
```
Please help. TIA

**Comment by pinnamur** [comment]
I'm seeing the same error. It is triggered by latest merged PR.

**Comment by floscha** [comment]
Like the traceback suggests, the error is caused by a typo in line 135. Instead of 
`def last_block(self) -> Dict[str: Any]:`
this line should be
`def last_block(self) -> Dict[str, Any]:`.

Also, for this fix to work, you have to change the Dockerfile from pulling the GitHub repo to using your local code. So simply comment out this line:
`&& git clone https://github.com/dvf/blockchain.git /app \`
and insert
`COPY blockchain.py Pipfile /app/`
before the RUN block.

Then you should be able to build and run the Dockerfile as usual.

**Comment by shubhamoy** [comment]
Thanks a ton :) It worked like charm!

**Comment by Endogen** [comment]
This could have been fixed already. There is a PR for that issue: https://github.com/dvf/blockchain/pull/30
