### ISSUE TITLE
Write Tests

### ISSUE THREAD

**Issue by dvf** [dvf/blockchain#4]
We should write some tests...

**Comment by cdax** [comment]
I'm willing to pick this up. Planning to use https://docs.python.org/3.6/library/unittest.html I'll start working on a list of test cases, I'll share them with all of you here when I'm done.

**Comment by dawran6** [comment]
Hey @cdax I'd like to help too. Perhaps I could share some of tasks. If you haven't started, I could to pick this up too.

Also, personally I prefer [PyTest](https://docs.pytest.org/en/latest/) just because of familiarity. Though I know it'll add extra dependencies into the project, they are just for developer use case so I don't really worry about it. What's your thought? @dvf @cdax

**Comment by dvf** [comment]
Hey @dawran6 I've written some basic tests, feel free to pick up.
