### ISSUE TITLE
Question | Not an issue

### ISSUE THREAD

**Issue by Logic-gate** [dvf/blockchain#54]
Hey,

Just out of pure curiosity, if I were to add a `data` field to the block, what would be the adequate minimum size limit that would work without breaking the internet? I say size and not length because I am interested in storing chunks of binary(3-5mb) each. Is this even possible?

Cheers,

**Comment by dvf** [comment]
I'm guessing you mean a maximum size limit. Since we're just using plain old HTTP and Flask, it really depends on how you're planning to host this in production. I suggest running Flask behind gunicorn and nginx. 

You can then define these limits in gunicorn and nginx:

- gunicorn: http://docs.gunicorn.org/en/stable/settings.html
- nginx: https://stackoverflow.com/questions/26717013/how-to-edit-nginx-conf-to-increase-file-size-upload
