### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by abitofco** [dvf/blockchain#55]
Hello,

I am a n00b at python and I C&P blockchain.py into a file on my Ubuntu server running on an OrangePi PC.  The OS is Armbian with Ubuntu Server 16.04.  I followed the tutorial on HackerNoon as well.

The error:

File "blockchain.py", line 7, in <module>
  import requests
ModuleNotFoundError: No module named 'requests'

Any ideas would be helpful, I really like how this integrates HTTP requests when other examples I found do not.

**Comment by bcambel** [comment]
`pip install requests`

**Comment by abitofco** [comment]
bcambel,

Thank you for the reply!  Sadly I have followed the README already and just did a clean install and followed the steps again, still no luck and same error.  I also did `pip install requests` and got "Requirement already satisfied" on the 5 items it lists. Retried `pipenv run python blockchain.py` and got the same error again.

n00b question, the `pipenv install` doesn't need anything after it?

**Comment by bcambel** [comment]
@abitofco I think the missing step is after the `pipenv install` you have to run `pipenv shell` which will activate the virtualenvironment

**Comment by abitofco** [comment]
@bcambel I ran `pipenv shell` and still got the same error.  I will try this on a full version of Ubuntu Server running on a laptop, not an OrangePi, it's too bad the OrangePi's are cheap lol

**Comment by Endogen** [comment]
This could be a problem with different Python versions: If you installed the module, then i guess for a different Python version then you run the script with. If you installed it via `pip` then please see the output from `pip --version` and compare the Python version that is mentioned there with the Python version you run the script with. If you run it with `python blockchain.py` then check the Python version with `python --version`. The versions have to be the same.

For me, if i install modules then with `pip3.6 install <module_name>` and i run scripts with `python3.6 <script>`. I would have the same error as you if i would install it with the mentioned pip version but then run the script with `python <script>` instead of `python3.6 <script>`

**Comment by abitofco** [comment]
@Endogen I'm not sure which module you are referring to.

`pip --version` returns Python2.7; `python --version` returns Python2.7.12

When I installed Python3.6 I found and followed these instructions:
`sudo add-apt-repository ppa:jonathonf/python-3.6
sudo apt-get update
sudo apt-get install python3.6`

I then did `sudo apt-get install python-pip` and then installed setuptools and pipenv.

**Comment by abitofco** [comment]
I have this running on 2 OrangePi's now.  It turns out I needed to run `sudo pip install requests` and `sudo pip install flask`

**Comment by phonerefer** [comment]
I am running a python app in Ubuntu server and i am getting same error. But! same app is running fin in my local machine.
```
  File "app.py", line 10, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request
````
Don't understand what is problem is.
