### ISSUE TITLE
Jesus christ, just merge all the god damn shit!

### ISSUE THREAD

**Issue by Endogen** [dvf/blockchain#61]
@dvf I really hope you're not working in real life like you do here... 19 open pull requests? You wanted collaboration and got it - seems like you don't know what to do with it!

Really, i understand that this is your project and you don't have to do anything you don't want to but then state that. That's not what you did. You requested ports and you got them. Now it's your turn(?). TIME TO MERGE BROTHER!! You seem to absolutely not give a shit that people care about this project.

Sure, they all can just fork it and play around but your project aggregates people that really like it and want to contribute and bring this idea further. Now what you do is, not give a shit about all of that.

That's surely a valid decision but not the one with the most brains bro. I really hope you're better organized in real life, really...

This is one of those things that absolutely show that you are not capable of getting shit done - which is of course just my personal subjective opinion.

**Comment by dvf** [comment]
Hey @Endogen 

Some of the ports are lacking tests and peer reviews. I've mentioned that on some of them. I've also added a call for collaborators to help review these ports as I'm not an expert in other languages and I'd feel more comfortable if others took a second look. I'm also questioning whether it's a better idea to link to other projects in the README instead of hosting ports that can't be actively maintained.

We're also working on Part II, you can take a peak at the branch: `partii-sanic`, or get involved. I've added a timeline in a separate issue. It's likely that Part II will come with a bunch of changes.

Lastly, I don't appreciate your disparaging comments. This isn't my full time job but I like helping people out when I can. Your energy would be better spent helping out with the project instead of criticizing me.

**Comment by dvf** [comment]
I'm going to leave this issue open, if anyone would like to help out:

- Increase test coverage
- Reviewing PRs

**Comment by Endogen** [comment]
I think this project just doesn't hold up to the expectations i had in the beginning. I'm not saying you fucked up completely but helping out in this is kind of like running against a wall... The third time you do it, you realize it's better to bypass it.

**Comment by SalvorinFex** [comment]
@Endogen you're an ass!  
Just because people don't work on things according to your timetable, doesn't call for crass and inflammatory remarks.  You need to chill out, dude!

**Comment by Endogen** [comment]
I wrote what i felt and i stand by it.

Was it to hard? Yep. Was it inappropriate? Maybe. Do i care? Nope. Is it ok to use the language i used? Well, for me, i actually like to talk like that. Not all the time, but if i feel like it, i will do it. And you know what, if you feel offended by it, then i think you should really thing about why you feel offended by someone that you don't know and that doesn't know you. All you do is reading words from a stranger on a fucking screen dude... Just start to worry about stuff that really matters already...

Would i change what i wrote? Nope. At the time of writing, it was exactly what i felt and think about it: directly after that post, he closed / answered all issues on github and posted an implementation roadmap. Maybe - just maybe - it opened his eyes a bit to the realization that you kind of have some responsibility if you maintain a project here... As i already wrote, you can do what ever you like (it's like in reallife) but some actions are not exactly wise.

**Comment by SalvorinFex** [comment]
I get it, we all have frustrations from time to time.  This isn't just some forum, though, there's more of a professional atmosphere here, but I am glad you came around to realizing that.

**Comment by dvf** [comment]
@Endogen you sound like you’re 12 years old. Learn to speak to people with respect. I have a full time job, and have a limited time to help folks. If you enjoyed the tutorial then try contribute instead of whining about your point of view. 

I’ve had a call for collaborators issue up since this project started and nobody has applied. And the implementation roadmap was opened weeks ago if you bothered to look. 

The spirit of this project, and open source isn’t suited to uncollaborative, rude people, so take your bad vibes elsewhere.

**Comment by Endogen** [comment]
Who tells you i'm not 12 years old? xD

**Comment by Endogen** [comment]
No honestly, i do not think that i have to learn to speak to people with respect. I think i'm pretty good at that already. It's just that i speak with respect to people that i respect, you know. And only to them.

But i guess we all can agree on the fact that there is nothing more to say on this matter, since this discussion doesn't add to anything related to this project (as you demanded, i will gladly leave). All we do right now is intellectually and emotionally try to win - which is stupid and childish of course. My last words are (yah i know sounds like im 10 right ;) ): I'm sorry that i posted this issue and i do not think that this sounds or is childish, where i come from, it's called an apology and can never be wrong. I still stand for the content tho - i just should not have posted it.

Prost!

**Comment by panduit-ccgr** [comment]
Hi, when I attempt to run the code in master I get and error
File "/Users/cgriffin1/Downloads/blockchain-master/blockchain.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>> 

Where can I find the requests module?
